name: evince
version: git
summary: Document viewer for popular document formats
description: |
  This is a document viewer for the GNOME desktop.
  It supports the following document formats: PDF, PS, EPS, XPS, DjVu, TIFF, DVI (with SyncTeX), and Comic Books archives (CBR, CBT, CBZ, CB7).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  evince:
    interface: dbus
    bus: session
    name: org.gnome.Evince

passthrough:
  layout:
    /usr/share/xml/iso-codes:
      symlink: $SNAP/gnome-platform/usr/share/xml/iso-codes

apps:
  evince:
    command: desktop-launch evince
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Evince.desktop
  evince-previewer:
    command: desktop-launch evince-previewer
    plugs:
      - avahi-observe
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Evince-previewer.desktop

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  evince:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    plugin: meson
    meson-parameters:
       - --prefix=/snap/evince/current/usr
       - -Dnautilus=false
       - -Dgtk_doc=false
       - -Dintrospection=false
    organize:
      snap/evince/current/usr: usr
    build-packages:
      - appstream
      - intltool
      - gnome-pkg-tools
      - yelp-tools
      - gtk-doc-tools
      - libx11-dev
      - libarchive-dev
      - libcairo2-dev
      - libgtk-3-dev
      - libgail-3-dev
      - libglib2.0-dev
      - libgspell-1-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libsecret-1-dev
      - libxml2-dev
      - libsm-dev
      - zlib1g-dev
      - libpoppler-glib-dev
      - libspectre-dev
      - libtiff-dev
      - libdjvulibre-dev
      - libkpathsea-dev
      - libgxps-dev
      - autotools-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - gsettings-desktop-schemas-dev
      - gnome-common
      - dh-apparmor
    prime:
      - "-usr/lib/*.a"
      - "-usr/lib/mozilla"
      - "-usr/lib/pkgconfig"
      - "-usr/lib/systemd"
      - "-usr/lib/evince/4/backends/*.a"
      - "-usr/share/appdata"
  libraries:
    plugin: nil
    stage-packages:
      - libarchive13
      - libpoppler-glib8
      - libpoppler73
      - libnss3
      - libnspr4
    prime:
      - "usr/lib/*/libarchive.so.*"
      - "usr/lib/*/libpoppler-glib.so.*"
      - "usr/lib/*/libpoppler.so.*"
      - "usr/lib/*/libnss3.so"
      - "usr/lib/*/libnssutil3.so"
      - "usr/lib/*/libsmime3.so"
      - "usr/lib/*/libnspr4.so"
      - "usr/lib/*/libplc4.so"
      - "usr/lib/*/libplds4.so"
